apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
--- 
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: ngnix
    image: ngnix
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/shar/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static-pvc    


    