apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-pvc
spec:
  storageClassName: "ebs-sc" # Empty string must be explicitly set otherwise default StorageClass will be set
  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
--- 
apiVersion: v1
kind: Pod
metadata:
  name: frontend-dynamic
  labels:
   project: expense-dynamic
   environmet: dev-dynamic
   version: "3.0"
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage-dynamic
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage-dynamic
    persistentVolumeClaim:
      claimName: ebs-dynamic-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: loadbalacer
spec:
  type: LoadBalancer
  selector:
    project: expense-dynamic
    environmet: dev-dynamic
    version: "3.0"
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80
      nodePort: 30008

    


    