apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "efs-sc"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
   project: expense-efs
   environmet: dev-efs
   version: "2.0"
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-dynamic-claim
---
kind: Service
apiVersion: v1
metadata:
  name: loadbalacer-efs
spec:
  type: LoadBalancer
  selector:
    project: expense-efs
    environmet: dev-efs
    version: "2.0"
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80
      nodePort: 30008
