apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: Soumya
          value: "Hello from the environment"
        - name: farewell
          value: "Such a sweet sorrow"
