kind: Service
apiVersion: v1
metadata:
  name: loadbalacer
spec:
  type: LoadBalancer
  selector:
    project: expense
    environmet: dev
    version: "2.0"
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80
      nodePort: 30007
---

kind: Pod
apiVersion: v1
metadata:
  name: backend-np
  labels:
    project: expense
    environmet: dev
    version: "2.0"
spec:
  containers:
    - name: nginx
      image: nginx
      
