kind: Service
apiVersion: v1
metadata:
  name: nodeport
spec:
  type: NodePort
  selector:
    project: expense
    environmet: dev
    version: "1.0"
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80
      nodePort: 3007
---

kind: Pod
apiVersion: v1
metadata:
  name: backend
  labels:
    project: expense
    environmet: dev
    version: "1.0"
spec:
  containers:
    - name: nginx
      image: nginx
      
