apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expenseinfra
  labels:
    app: backend
    tier: backend
    project: expense
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec:
      containers:
      - name: nginx
        image: joindevops/backend:1.0.0
        

---
kind: Service
apiVersion: v1
metadata:
  name: service
  namespace: expenseinfra
spec:
  selector:
    app: backend
    tier: backend
    project: expense
  ports:
    - protocol: TCP
      port: 8080 #service port
      targetPort: 8080
      